### ISSUE TITLE
Verbosity; lack of detail.

### ISSUE THREAD

**Issue by jcricaro** [jaenelleisidro/hiring-guidelines#6]
For a hiring guideline to be actually helpful for companies to use, a simple set of stack, simply, isn't enough.

e.g.

A php developer, doesn't only need to understand what _PHP_, _JS_, _CSS_, etc is.
He/she should also understand certain principles/patterns. Like the basics: _CRUD_, _ORM_.

If these stuff are considered general, then disregard this.

**Comment by jaenelleisidro** [comment]
yes the best pa rin na may crud at orm.
but i think minimum requirements para makapasok ka sa technical interview without kasi yung unang titingin yung hr, at least siguro may php js at css for a php developer (junior).
although siguro if mid level, or senior dapat talaga may orm,crud and other frameworks na.
for now this diagram is for minimum requirements and assumes na junior position. thanks for raising this and let me know your thoughts.

**Comment by jcricaro** [comment]
@jaenelleisidro Great.
